import { Hairstyle } from './types';

export const HAIRSTYLES: Hairstyle[] = [
  {
    id: 'pixie',
    name: 'Pixie Cut',
    previewImage: 'https://images.squarespace-cdn.com/content/v1/5702abebd210b8e9fd0df564/32e1cf93-5b05-4583-a3ab-da7fb6c97c52/Swanky-Malone-Pixie-Cut-Short.jpg$0',
    prompt: 'Give the person in the image a chic and short pixie cut hairstyle. Keep their face and the background intact.',
    gender: 'female',
  },
  {
    id: 'bob',
    name: 'Classic Bob',
    previewImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_6qjaveVKx8rWc6kU5qAT3hLAuscHEtw0Vg&s$0',
    prompt: 'Change the person\'s hair to a classic, chin-length bob hairstyle. Maintain their facial features and the background.',
    gender: 'female',
  },
  {
    id: 'long_wavy',
    name: 'Long & Wavy',
    previewImage: 'https://img.lazcdn.com/g/p/d160de888c654898f525a9f2a40d5c91.jpg_720x720q80.jpg$0',
    prompt: 'Transform the person\'s hair into a long, wavy hairstyle with natural-looking waves. Keep their face and the background intact.',
    gender: 'female',
  },
  {
    id: 'man_bun',
    name: 'Man Bun',
    previewImage: 'https://vagazine.com/vaga_v3/wp-content/uploads/2024/03/man-bun-hair-man-771x1024.jpeg',
    prompt: 'Give the person in the image a stylish man bun hairstyle. Ensure it looks natural on them and keep the background.',
    gender: 'male',
  },
  {
    id: 'curly_afro',
    name: 'Curly Afro',
    previewImage: 'https://content.latest-hairstyles.com/wp-content/uploads/curly-afro-with-the-perfect-ringlets-for-men.jpg',
    prompt: 'Change the hairstyle to a voluminous and beautiful curly afro. Maintain their facial features and the background.',
    gender: 'unisex',
  },
  {
    id: 'braids',
    name: 'Cornrow Braids',
    previewImage: 'https://i.pinimg.com/736x/a1/ef/36/a1ef36f5f26f1b725fb4127a036c14d8.jpg',
    prompt: 'Give the person in the image intricate cornrow braids. The style should be neat and stylish. Keep the background.',
    gender: 'unisex',
  },
  {
    id: 'mohawk',
    name: 'Faux Hawk',
    previewImage: 'https://i.pinimg.com/736x/cf/62/00/cf6200a886fe2df62abc91f5bc455624.jpg',
    prompt: 'Style the person\'s hair into a modern faux hawk. Keep the sides shorter. Maintain facial features.',
    gender: 'male',
  },
  {
    id: 'silver',
    name: 'Silver Waves',
    previewImage: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_E70L4Z-PEyJbY0uFe3pL0-fd_Bf0A-hxQw&s$0',
    prompt: 'Change the person\'s hair to a stylish, wavy hairstyle with a metallic silver color. Keep their face and the background intact.',
    gender: 'female',
  },
  {
    id: 'curtain_bangs',
    name: 'Curtain Bangs',
    previewImage: 'https://images.squarespace-cdn.com/content/v1/633c62a0f0e6e662d4794c5a/3ac769bb-5371-4c67-bb61-367d50426e61/fine-hair-curtain-bangs.jpg',
    prompt: 'Give the person in the image trendy curtain bangs with a layered cut. Maintain their facial features and the background.',
    gender: 'female',
  },
  {
    id: 'shag_mullet',
    name: 'Shag Mullet',
    previewImage: 'https://i.pinimg.com/736x/48/ee/51/48ee51e38e33d98f2b5fd1d91283d9cf.jpg',
    prompt: 'Transform the person\'s hairstyle into a modern shag mullet, with choppy layers and texture. Keep the background.',
    gender: 'female',
  },
  {
    id: 'crew_cut',
    name: 'Crew Cut',
    previewImage: 'https://cdn.shopify.com/s/files/1/0899/2676/2789/files/Crew_Cut_with_Tapered_Sides.jpg',
    prompt: 'Change the person\'s hair to a classic, short crew cut. Keep the top slightly longer than the sides. Keep the background.',
    gender: 'male',
  },
  {
    id: 'slick_back',
    name: 'Slick Back',
    previewImage: 'https://i.pinimg.com/474x/ee/13/64/ee136439d7e7abfa32a4b295814a9bc0.jpg',
    prompt: 'Give the person a sleek, slicked-back hairstyle. It should look neat and polished. Maintain their facial features.',
    gender: 'male',
  },
  {
    id: 'see_through_bangs',
    name: 'See-Through Bangs',
    previewImage: 'https://i.pinimg.com/736x/b3/f7/ee/b3f7ee4ed9ded64c126235199dd2fd17.jpg',
    prompt: 'Give the person in the image Korean-style see-through bangs. The bangs should be light and wispy, paired with long hair. Keep the face and background.',
    gender: 'female',
  },
  {
    id: 'two_block',
    name: 'Two-Block Cut',
    previewImage: 'https://cdn.shopify.com/s/files/1/0899/2676/2789/files/The_Two_Block_Haircut.jpg',
    prompt: 'Change the person\'s hairstyle to a popular Korean two-block cut. The sides and back should be short, with longer, textured hair on top. Maintain their facial features.',
    gender: 'male',
  },
  {
    id: 'hime_cut',
    name: 'Hime Cut',
    previewImage: 'https://i.pinimg.com/564x/57/62/45/576245fe1360f41d23c69f1e8f5ca2b7.jpg',
    prompt: 'Transform the person\'s hair into a Japanese Hime cut. The style should feature straight, blunt bangs, cheek-length sidelocks, and long straight hair in the back. Keep the background intact.',
    gender: 'female',
  },
  {
    id: 'wolf_cut',
    name: 'Wolf Cut',
    previewImage: 'https://behindthechair.com/wp-content/uploads/2025/06/Photo-Credit-Instagram-via-@-chellsiedanielles-.png',
    prompt: 'Give the person a trendy wolf cut hairstyle with lots of choppy, textured layers on top and longer hair in the back. The style should have a messy, voluminous feel. Maintain facial features and hair color.',
    gender: 'unisex',
  },
  {
    id: 'textured_crop',
    name: 'Textured Crop',
    previewImage: 'https://cdn.shopify.com/s/files/1/0635/7159/1424/files/Textured_French_Crop_Haircut.jpg?v=1748363822$0',
    prompt: 'Style the person\'s hair into a modern textured crop, popular in East Asia. The sides should be faded, and the top should be textured and styled forward. Keep the background.',
    gender: 'male',
  },
  {
    id: 'soft_waves',
    name: 'Taiwanese Soft Waves',
    previewImage: 'https://i.pinimg.com/236x/af/b3/f3/afb3f308955d3d399de310ea259ad1c3.jpg',
    prompt: 'Change the person\'s hairstyle to long, soft waves, creating an elegant and gentle look often seen in Taiwanese dramas. Keep their face and the background intact.',
    gender: 'female',
  },
  {
    id: 'korean_wavy',
    name: 'Korean Wavy',
    previewImage: 'https://i.pinimg.com/736x/07/20/36/072036245f935109040df51ddcf68105.jpg',
    prompt: 'Change the person\'s hairstyle to long, wavy, creating an elegant and gentle look often seen in Korean dramas. Keep their face and the background intact.',
    gender: 'female',
  },
  {
    id: 'pompadour',
    name: 'Classic Pompadour',
    previewImage: 'https://i0.wp.com/hairinmotion.co.uk/wp-content/uploads/2022/10/Corte-masculino-estilo-Pompadour-o-Tupe.jpg',
    prompt: 'Give the person in the image a classic pompadour hairstyle with short sides and voluminous, swept-back hair on top. Keep the background intact.',
    gender: 'male',
  },
  {
    id: 'fade_textured',
    name: 'Fade with Texture',
    previewImage: 'https://cdn-nearcut.s3.amazonaws.com/FH42R5/large_3BEAD674-F49B-49D8-B0AE-1BA3CF03D5F0.jpeg',
    prompt: 'Change the person\'s hairstyle to a high fade on the sides with a textured, messy top. Maintain their facial features.',
    gender: 'male',
  },
  {
    id: 'side_part',
    name: 'Classic Side Part',
    previewImage: 'https://cdn.shopify.com/s/files/1/0899/2676/2789/files/Classic_Side_Part.jpg',
    prompt: 'Give the person a classic side part hairstyle. The hair should be neatly combed to one side, with a clean, defined part. Keep the background.',
    gender: 'male',
  },
  {
    id: 'bald_head',
    name: 'Bald Head',
    previewImage: 'https://www.shutterstock.com/image-photo/human-alopecia-hair-loss-adult-600nw-98846069.jpg',
    prompt: 'Make the person in the image completely bald. Remove all hair from their head for a clean-shaven look. Keep their facial features and the background intact.',
    gender: 'male',
  },
];